name: weather_pipeline
version: "1.0.0"
config-version: 2

profile: weather_pipeline

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  weather_pipeline:
    staging:
      +materialized: view
      +tags: ["weather", "staging"]
      +schema: staging
    marts:
      +materialized: table
      +tags: ["weather", "marts"]
      +schema: analytics
